- name: 'install docker dependencies'
  apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    state: latest
    update_cache: true

- name: 'add docker APT key'
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: "add docker APT repo"
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
          
- name: 'install docker'
  apt:
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    state: latest

- name: "add user to the docker group"
  user:
        name: "jenkins-vm"
        group: docker
        state: present

- name: "install python3"
  apt:
    name: python3
    state: latest
    update_cache: true

- name: "install pip3"
  apt:
    name: python3-pip
    state: latest
    update_cache: true

- name: "install setuptools"
  pip:
    name: setuptools
    executable: pip3
    state: latest

- name: "install docker pip package"
  pip:
    name: docker
    state: latest