- name: "clone git repo" 
  git:
    repo: https://github.com/sc18kg/QA-PROJECT-2.git
    dest: /home/Kieron/QA-PROJECT-2
    update: yes

- name: "initialise swarm"
  docker_swarm:
    state: present

- name: "get swarm information"
  docker_swarm_info:
  register: swarm_info

- name: "get join token"
  add_host:
    name: "token"
    value: "{{ swarm_info['swarm_facts']['JoinTokens']['Worker'] }}"